# Use this script to add libraries to be used for this project
library(tidyverse)
library(broom)
library(vegan)
library(speedyseq)
library(rbiom)
library(rstatix)
library(ggbeeswarm)
library(ggprism)
library(scales)
library(microViz)
library(ANCOMBC)
library(ggrepel)
library(patchwork)
library(ZIR)
library(corrr)
library(ggtext)

writeLines(capture.output(sessionInfo()), "output/sessionInfo.txt")
